### ISSUE TITLE
After the transform i get a random generated asset name which doesn't get SEO ranking

### ISSUE THREAD

**Issue by Nielsvdel** [nystudio107/craft-imageoptimize-sharp#10]
### Describe the bug
After the transform i get a random generated asset name which doesn't get SEO ranking. For example this url: https://de9r8b87pka1e.cloudfront.net/eyJidWNrZXQiOiJiZW5pdGVjaC0yMDIzIiwia2V5IjoibWVkaWEvSG9tZXBhZ2UtaGVhZGVyL0t1bnN0c3RvZi1rb3ppam5lbi1CZW5pdGVjaC5wbmciLCJlZGl0cyI6eyJ3ZWJwIjp7InF1YWxpdHkiOjgwfSwicmVzaXplIjp7IndpZHRoIjoxMDkwLCJoZWlnaHQiOjY5MCwiZml0IjoiY292ZXIifSwic2hhcnBlbiI6dHJ1ZX19.

_** I already added an issue in the "nystudio107/craft-imageoptimize". There is was referred to the sharp repo. Hope this is the correct one._

### To reproduce
Steps to reproduce the behaviour:
1. Go to "https://benitech.nl/"
2. Try and download an image
3. See that the image doesn't have the filename that is added in the CMS.

### Expected behaviour
Would like to keep the correct filename so that the image also helps with the SEO ranking

### Versions
- Plugin version: "nystudio107/craft-imageoptimize": "4.0.5",
- Craft version:  4.5.11.1

**Comment by khalwat** [comment]
This is just how the particular implementation of Sharp works, that's what it generates. It's not something Image Optimize has any control over.
