### ISSUE TITLE
Setting focal point results in incorrect sharpjs config

### ISSUE THREAD

**Issue by almeric** [nystudio107/craft-imageoptimize-sharp#2]
Hi, 

We're using ImageOptimize with the Amazon Serverless Image Handler and we're running into issues whenever we set the Focal point in Craft.

Setting the Focal point to the top right (for instance) results in broken images (the image handler just returns an empty json object). I think the issue is with the generation of the `position` value in the json. (`SharpImageTransform.php:172`)

Setting the focal point to the top right gives the following resize object for example:
```
{
    "resize": {
        "width": 1440,
        "height": 810,
        "fit": "cover",
        "position": "top,right"
    }
}
```

According to the sharpjs docs (https://sharp.pixelplumbing.com/api-resize) valid values for position are: 

`top`, `right top`, `right`, `right bottom`, `bottom`, `left bottom`, `left`, `left top`.

It seems the order (`right top` vs `top right`) is important, as is the lack of a comma separator.

 If I manually change the `position` key to `right top` & re-encode the json the image works as expected.

**Comment by almeric** [comment]
@khalwat any updates on this?

**Comment by khalwat** [comment]
Should be an easy fix, sorry I missed your initial issue.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-imageoptimize-sharp/commit/aa07b9ad67ad15d5c7267ffe358242db7bb43312

**Comment by almeric** [comment]
No worries, thanks for the fix!
