### ISSUE TITLE
Position is not working for the image transform with the 'crop' mode

### ISSUE THREAD

**Issue by Romanavr** [nystudio107/craft-imageoptimize-sharp#8]
### Describe the bug
If you set transform to a position other than `center-center`, it won't work.
Generally the main problem is here: https://github.com/nystudio107/craft-imageoptimize-sharp/blob/5f23484cb25a8cd5808b0087c557ae1d04f160b7/src/imagetransforms/SharpImageTransform.php#L153
Here you get the focal-point and check if it's not empty on a line below. 
But the point is that focal-point is never `empty`.
https://github.com/craftcms/cms/blob/765737f194f05df8752ef3ca0b41da7245c1a27b/src/elements/Asset.php#L2404
If it's not set fot the asset, `->getFocalPoint()` will return us `[0.5, 0.5]`, which is simply equal to `center-center`.

### To reproduce
1. Use Sharp as a transformer
2. Upload any asset
3. Use transform with the `position` property, where the `position` will be different from `center-center`
For example:
```
{% set testAsset = craft.assets.id(123456).one() %}
{% set myTransform = {
    mode: 'crop',
    width: 500,
    height: 500,
    position: 'top-center'
} %}

<img src="{{ testAsset.url(myTransform) }}">
```
**4. The image will always be in the center** 

### Expected behaviour
The transformed image should change position

### Screenshots
![изображение](https://github.com/nystudio107/craft-imageoptimize-sharp/assets/3519951/c31c0bd8-311e-43df-8b8d-e7125ad8c827)
With force-set position to "top"
![изображение](https://github.com/nystudio107/craft-imageoptimize-sharp/assets/3519951/9b7ed2fe-fd9e-4d87-8cc1-5116a7229a63)

### Versions
- Plugin version: **ImageOptimize** 4.0.5, **Imageoptimize-Sharp** 4.0.1
- Craft version: 4.7.1

**Comment by Romanavr** [comment]
@khalwat Please check fix in PR -> https://github.com/nystudio107/craft-imageoptimize-sharp/pull/9

**Comment by khalwat** [comment]
Released as:

Craft 3: `1.0.12` -> https://github.com/nystudio107/craft-imageoptimize-sharp/releases/tag/1.0.12

Craft 4: `4.0.2` -> https://github.com/nystudio107/craft-imageoptimize-sharp/releases/tag/4.0.2
